version: '3.7'

services:

  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "9229:9229"
      - "84:80"
    expose:
      - "84"
    environment:
      - VIRTUAL_HOST=admin.local
      - VIRTUAL_PORT=80
    volumes:
      - ./admin:/var/app/current
    command: bash -c "/var/app/current/docker_init.sh admin local admin"

  carousel:
    container_name: carousel
    build:
      context: ./carousel
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=carousel.local
      - VIRTUAL_PORT=3000
    volumes:
      - ./carousel:/var/app/current
    command: bash -c "/var/app/current/docker_carousel_init.sh"

  akdb:
    container_name: akdb
    build:
      context: ./db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    user: "root"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    hostname: db
    volumes:
      - ./db/docker/data/db:/var/lib/mysql
      - ./db:/db

  nginx:
    container_name: nginx
    depends_on:
      - akdb
      - admin
      - carousel
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx:/nginx
